
name = "insight-hunter-v1-3-2"
main = "dist/worker.mjs"          # if bundling a Worker entry
compatibility_date = "2024-11-21"

[assets]
directory = "dist"                # serve built static assets (SPA)


# ---------- Environment Vars ----------
[vars]
NODE_ENV = "production"
APP_NAME = "Insight Hunter"

# ---------- KV Namespaces ----------
[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "your-kv-id-here"
preview_id = "your-kv-preview-id"

# ---------- R2 Buckets ----------
[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "insight-hunter-reports"

# ---------- D1 Database ----------
[[d1_databases]]
binding = "DB"
database_name = "insight_hunter_db"
database_id = "your-d1-id-here"

# ---------- Queues (optional) ----------
[[queues.producers]]
binding = "NOTIFY_QUEUE"
queue = "insight-hunter-events"

# ---------- Analytics Engine ----------
[[analytics_engine_datasets]]
binding = "AE"
dataset = "ANALYTICS_ENGINE"

[observability]
enabled = true